git-nginx:
  image: emarcs/nginx-git
  container_name: git-nginx
  ports:
    - 80:80
  volumes:
    - $PWD/repositories:/srv/git
    - $PWD/nginx/logs:/var/log/nginx
    # add your custom username and password (default is admin, admin)
    - $PWD/credentials/htpasswd:/srv/htpasswd
    # if you want to use a custom configuration
    - $PWD/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  environment:
    GIT_POSTBUFFER: 1048576
