test_srv:
  image: emarcs/nginx-git
  ports:
    - 80:80
  volumes:
    - /opt/docker/docker-nginx-git/srv/git:/srv/git
    - /opt/docker/docker-nginx-git/logs:/var/log/nginx
    # add your custom username and password (default is admin, admin)
    - ./htpasswd:/srv/htpasswd
    # if you want to use a custom configuration
    - ./default.conf:/etc/nginx/conf.d/default.conf
  environment:
    GIT_POSTBUFFER: 1048576
