nginx-git:
  image: jinro79/nginx-git:latest
  container_name: nginx-git
  restart: always
  ports:
    - 80:80
  volumes:
    - /srv/git:/srv/git
    - $PWD/nginx/logs:/var/log/nginx
    # add your custom username and password (default is admin, admin)
    - $PWD/nginx/conf.d/htpasswd:/etc/nginx/conf.d/htpasswd
    # if you want to use a custom configuration
    #- $PWD/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  environment:
    GIT_POSTBUFFER: 1048576
